# Generated by Django 4.2.7 on 2023-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('factory_year', models.IntegerField(blank=True, null=True, verbose_name='Ano Fabricação')),
                ('model_year', models.IntegerField(blank=True, null=True, verbose_name='Ano Modelo')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
