# Generated by Django 4.2.7 on 2023-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate_alter_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInvetory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(verbose_name='Carros em Estoque')),
                ('cars_value', models.FloatField(verbose_name='Valor Total em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Foto'),
        ),
    ]
