# Generated by Django 4.2.7 on 2023-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinvetory_alter_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bio do Carro'),
        ),
    ]
